### ISSUE TITLE
Always popup not enable in lsposed/exposed

### ISSUE THREAD

**Issue by Poco-cong** [Android1500/AndroidFaker#25]
Always Popup not enable in lsposed/exposed, But I already activated it

10-29 06:25:19.496  4842  4842 I EdXposed-Bridge: Loading modules from /data/app/~~kYfNFmIXeSKnlJBjshzGsw==/com.android1500.androidfaker--1IuSXdK8zAElCfuzqQ6hQ==/base.apk
10-29 06:25:19.514  4842  4842 I EdXposed-Bridge:   Loading class com.android1500.androidfaker.xposed.MainHook
10-29 06:25:19.565  4842  4842 E EdXposed-Bridge:     Failed to load class com.android1500.androidfaker.xposed.MainHook
10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: java.lang.UnsatisfiedLinkError: dlopen failed: library "libaf_native.so" not found
10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.System.loadLibrary(System.java:1664)

**Comment by Poco-cong** [comment]
> > Always Popup not enable in lsposed/exposed, But I already activated it
> > 10-29 06:25:19.496  4842  4842 I EdXposed-Bridge: Loading modules from /data/app/~~kYfNFmIXeSKnlJBjshzGsw==/com.android1500.androidfaker--1IuSXdK8zAElCfuzqQ6hQ==/base.apk
> > 10-29 06:25:19.514  4842  4842 I EdXposed-Bridge:   Loading class com.android1500.androidfaker.xposed.MainHook
> > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge:     Failed to load class com.android1500.androidfaker.xposed.MainHook
> > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: java.lang.UnsatisfiedLinkError: dlopen failed: library "libaf_native.so" not found
> > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
> > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
> > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.System.loadLibrary(System.java:1664)
> 
> Which version?

New version in release

**Comment by Android1500** [comment]
> > > Always Popup not enable in lsposed/exposed, But I already activated it
> 
> > > 10-29 06:25:19.496  4842  4842 I EdXposed-Bridge: Loading modules from /data/app/~~kYfNFmIXeSKnlJBjshzGsw==/com.android1500.androidfaker--1IuSXdK8zAElCfuzqQ6hQ==/base.apk
> 
> > > 10-29 06:25:19.514  4842  4842 I EdXposed-Bridge:   Loading class com.android1500.androidfaker.xposed.MainHook
> 
> > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge:     Failed to load class com.android1500.androidfaker.xposed.MainHook
> 
> > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: java.lang.UnsatisfiedLinkError: dlopen failed: library "libaf_native.so" not found
> 
> > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
> 
> > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
> 
> > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.System.loadLibrary(System.java:1664)
> 
> > 
> 
> > Which version?
> 
> 
> 
> New version in release 

Its cause when you modified code of app

**Comment by Poco-cong** [comment]
> > > > Always Popup not enable in lsposed/exposed, But I already activated it
> > 
> > 
> > > > 10-29 06:25:19.496  4842  4842 I EdXposed-Bridge: Loading modules from /data/app/~~kYfNFmIXeSKnlJBjshzGsw==/com.android1500.androidfaker--1IuSXdK8zAElCfuzqQ6hQ==/base.apk
> > 
> > 
> > > > 10-29 06:25:19.514  4842  4842 I EdXposed-Bridge:   Loading class com.android1500.androidfaker.xposed.MainHook
> > 
> > 
> > > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge:     Failed to load class com.android1500.androidfaker.xposed.MainHook
> > 
> > 
> > > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: java.lang.UnsatisfiedLinkError: dlopen failed: library "libaf_native.so" not found
> > 
> > 
> > > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
> > 
> > 
> > > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
> > 
> > 
> > > > 10-29 06:25:19.565  4842  4842 E EdXposed-Bridge: 	at java.lang.System.loadLibrary(System.java:1664)
> > 
> > 
> > > 
> > 
> > 
> > > Which version?
> > 
> > 
> > New version in release
> 
> Its cause when you modified code of app

I didn't modify the app
![Uploading Screenshot_20231031-121409_Google_Play_Store.png…]()

**Comment by Poco-cong** [comment]
![Screenshot_20231031-121409_Google_Play_Store](https://github.com/Android1500/AndroidFaker/assets/66915395/0000b9c1-f3bf-4428-90b0-10b46f0bd642)
